document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/jquery-1.7.2.min.js'></scr" + "ipt>");
// document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/jquery-migrate-1.2.1.min.js'></scr" + "ipt>");
// document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/jquery-1.10.2.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/jquery-ui.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/jquery_backstretch.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/jquery.autocomplete.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/jquery.animate-shadow-min.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/jquery-bbq.min.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/lib/Class.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/movies/main.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/com_movies/AbstractPage.js'></scr" + "ipt>");
//document.writeln("<scr" + "ipt type='text/javascript' src='/html/footer/footer.js'></scr" + "ipt>");
//document.writeln("<scr" + "ipt type='text/javascript' src='/html/topNav/topNav.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/func/movieslider/movieslider.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/func/movielist/movielist.js'></scr" + "ipt>");
// document.writeln("<scr" + "ipt type='text/javascript' src='/src/func/movielist/movielisttest.json'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/movies/overlays/movieTrailers/movieTrailers.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/movies/overlays/oldMovieTrailers/oldMovieTrailers.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/movies/overlays/other_search_list/other_search_list.js'></scr" + "ipt>");
document.writeln("<scr" + "ipt type='text/javascript' src='/src/func/template.js'></scr" + "ipt>");
